force-app/main/default/objects/Country_Layer__c/Country_Layer__c.object-meta.xml
<CustomObject>
    <label>Country Layer</label>
    <nameField>
        <label>Country Layer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Layer__c/fields/Alpha2Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha2Code__c</fullName>
    <label>Alpha 2 Code</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_Layer__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <externalId>true</externalId>
    <label>Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Layer__c/fields/Last_Updated_From_API__c.field-meta.xml
<CustomField>
    <fullName>Last_Updated_From_API__c</fullName>
    <label>Last Updated From API</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Country_Layer__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <label>Regional Blocs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/InsertCountriesQueueable.cls
public class InsertCountriesQueueable implements Queueable {

    private List<APIRestInput.CountryData> countries;

    public InsertCountriesQueueable(List<APIRestInput.CountryData> countries) {
        this.countries = countries;
    }

    public void execute(QueueableContext context) {
        List<Country_Layer__c> countriesToInsert = new List<Country_Layer__c>();

        for (APIRestInput.CountryData cd : countries) {
            system.debug('@regionalblocks ' + cd.regionalBlocs);
            //Regional blocks are not found in WS
            String blocs = cd.regionalBlocs != null && !cd.regionalBlocs.isEmpty()
                ? String.join(cd.regionalBlocs, ',') : '';

            Country_Layer__c country = new Country_Layer__c(
                Name = cd.name,
                Alpha2Code__c = cd.alpha2Code,
                Alpha3Code__c = cd.alpha3Code,
                Capital__c = cd.capital,
                Region__c = cd.region,
                RegionalBlocs__c = blocs,
                Last_Updated_From_API__c = System.now()
            );

            countriesToInsert.add(country);
        }

        if (!countriesToInsert.isEmpty()) {
            insert countriesToInsert;
        }
    }
}