force-app/main/default/objects/Country_Layer__c/Country_Layer__c.object-meta.xml
<CustomObject>
    <label>Country Layer</label>
    <nameField>
        <label>Country Layer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Layers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Layer__c/fields/Alpha3Code__c.field-meta.xml
<CustomField>
    <fullName>Alpha3Code__c</fullName>
    <externalId>true</externalId>
    <label>Alpha 3 Code</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_Layer__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <label>Regional Blocs</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/country_code__c.field-meta.xml
<CustomField>
    <fullName>country_code__c</fullName>
    <label>country code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadGateway.cls
public class LeadGateway {

    
    public static map<String,Country_Layer__c> compareCountryData (List<Lead>triggerNew) {

        Set<String> alpha3Codes = new Set<String>();
        for (Lead l : triggerNew) {
            if (l.Country_Code__c != null) {
                alpha3Codes.add(l.Country_Code__c);
            }
        }
    
        if (alpha3Codes.isEmpty()) return null;
    
       
        Map<String, Country_Layer__c> countryMap = new Map<String, Country_Layer__c>(
            [SELECT Alpha3Code__c, Region__c, Capital__c, RegionalBlocs__c
             FROM Country_Layer__c
             WHERE Alpha3Code__c IN :alpha3Codes]
        );
        return countryMap;
    
    }
    
    public static void updateCountryData(Country_Layer__c cl) {
        //update lead fields
        //l.Region__c = cl.Region__c;
        //l.Capital__c = cl.Capital__c;
        //l.Regional_Blocs__c = cl.RegionalBloc__c;
    }
    
}